### ISSUE TITLE
Consider adding cursors for better UX

### ISSUE THREAD

**Issue by rchillard** [rchillard/sane.css#1]
Consider code from Chris Ferdinandi, re: cursors:

```css
button,
[type="button"],
[type="reset"],
[type="submit"],
[type="image"],
[type="checkbox"],
[type="radio"],
summary {
	cursor: pointer;
}
```
